defaults:
  - base_train_config # Reference the schema
  - _self_

# Model configuration
patch_size: 16
embed_dim: 192 # Tiny variant
decoder_embed_dim: 96
compile: true

# Training parameters
batch_size: 512
# batch_size: 8
total_samples: 1_000_000 # ~400 epochs on ImageNette
amp: true
grad_clip: 1.0
mask_ratio: 0.75
lr: 3e-4
seed: 42
profiler: false

# Data configuration
data:
  root: /home/yberreby/datasets/imagenette # Will be overridden by CLI
  train_val_split: 0.9
  pin_memory: false
  # num_workers will default to min(CPU_count, 16)

# Logging and checkpointing
log_dir: runs
ckpt_dir: checkpoints
samples_per_viz: 100_000
samples_per_val: 100_000
samples_per_ckpt: 100_000

pretrained_path: "ckpt/mae_tiny_400e.pth.tar" # Optional
