defaults:
  - base_train_config
  - _self_

# Training parameters
batch_size: 128
total_samples: 100_000
lr: 3e-4
warmup_ratio: 0.1
weight_decay: 0.01
beta1: 0.9
beta2: 0.999

# Logging and checkpointing
samples_per_viz: 10_000
samples_per_val: 10_000
samples_per_ckpt: 100_000
